-- MySQL Script generated by MySQL Workbench
-- Sat Apr  3 09:42:38 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema reserveaqui
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `reserveaqui` ;

-- -----------------------------------------------------
-- Schema reserveaqui
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reserveaqui` DEFAULT CHARACTER SET utf8 ;
USE `reserveaqui` ;

-- -----------------------------------------------------
-- Table `reserveaqui`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`cliente` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`reserva` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `horario_chegada_esperada` TIME NOT NULL,
  `data_reserva` DATETIME NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `avaliacao` INT NULL,
  PRIMARY KEY (`id_reserva`, `cliente_id_cliente`),
  INDEX `fk_reserva_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `reserveaqui`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`mesa` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`mesa` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `qtd_cadeiras` INT NOT NULL,
  `nome_mesa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`turno` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`turno` (
  `id_turno` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(90) NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_fim` TIME NOT NULL,
  PRIMARY KEY (`id_turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`restaurante` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`restaurante` (
  `id_restaurante` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `minutos_limite_chegada` INT NULL,
  PRIMARY KEY (`id_restaurante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`reserva_turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`reserva_turno` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`reserva_turno` (
  `reserva_id_reserva` INT NOT NULL,
  `turno_id_turno` INT NOT NULL,
  PRIMARY KEY (`reserva_id_reserva`, `turno_id_turno`),
  INDEX `fk_turno_has_reserva_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  INDEX `fk_turno_has_reserva_turno_idx` (`turno_id_turno` ASC) VISIBLE,
  CONSTRAINT `fk_turno_has_reserva_turno`
    FOREIGN KEY (`turno_id_turno`)
    REFERENCES `reserveaqui`.`turno` (`id_turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_has_reserva_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `reserveaqui`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`status` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`status` (
  `id_status` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`mesa_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`mesa_reserva` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`mesa_reserva` (
  `mesa_id_mesa` INT NOT NULL,
  `reserva_id_reserva` INT NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`mesa_id_mesa`, `reserva_id_reserva`),
  INDEX `fk_mesa_has_reserva_reserva1_idx` (`reserva_id_reserva` ASC) VISIBLE,
  INDEX `fk_mesa_has_reserva_mesa1_idx` (`mesa_id_mesa` ASC) VISIBLE,
  INDEX `fk_mesa_reserva_status1_idx` (`id_status` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_has_reserva_mesa1`
    FOREIGN KEY (`mesa_id_mesa`)
    REFERENCES `reserveaqui`.`mesa` (`id_mesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_has_reserva_reserva1`
    FOREIGN KEY (`reserva_id_reserva`)
    REFERENCES `reserveaqui`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_reserva_status1`
    FOREIGN KEY (`id_status`)
    REFERENCES `reserveaqui`.`status` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reserveaqui`.`dias_funcionamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reserveaqui`.`dias_funcionamento` ;

CREATE TABLE IF NOT EXISTS `reserveaqui`.`dias_funcionamento` (
  `id_dia` INT NOT NULL,
  `restaurante_id_restaurante` INT NOT NULL,
  `dia_descricao` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_dia`, `restaurante_id_restaurante`),
  INDEX `fk_dias_funcionamento_restaurante1_idx` (`restaurante_id_restaurante` ASC) VISIBLE,
  CONSTRAINT `fk_dias_funcionamento_restaurante1`
    FOREIGN KEY (`restaurante_id_restaurante`)
    REFERENCES `reserveaqui`.`restaurante` (`id_restaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use `reserveaqui`;

INSERT into restaurante (login, senha, minutos_limite_chegada) values ('admin', '654321', 30);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (0, 1, 'Domingo', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (1, 1, 'Segunda-feira', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (2, 1, 'Terça-feira', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (3, 1, 'Quarta-feira', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (4, 1, 'Quinta-feira', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (5, 1, 'Sexta-feira', 1);
INSERT INTO dias_funcionamento (id_dia, restaurante_id_restaurante, dia_descricao, ativo) values (6, 1, 'Sábado', 1);

INSERT INTO `reserveaqui`.`CLIENTE` (`id_cliente`, `login`, `senha`, `nome`, `email`, `celular`) VALUES ('1', 'talita.melo', '123', 'Talita Melo', 'talita@email.com', '31999999998');

INSERT INTO `reserveaqui`.`status` (`id_status`, `descricao`) VALUES ('1', 'Reservado');
INSERT INTO `reserveaqui`.`status` (`id_status`, `descricao`) VALUES ('2', 'Em uso');
INSERT INTO `reserveaqui`.`status` (`id_status`, `descricao`) VALUES ('3', 'Finalizado');
INSERT INTO `reserveaqui`.`status` (`id_status`, `descricao`) VALUES ('4', 'Cancelado');

INSERT INTO `reserveaqui`.`mesa` (`id_mesa`, `qtd_cadeiras`, `nome_mesa`) VALUES ('1', '5', 'A');

INSERT INTO `reserveaqui`.`reserva` (`id_reserva`, `horario_chegada_esperada`, `data_reserva`, `cliente_id_cliente`) VALUES ('1', '10:30:00', '2021-04-22', '1');

INSERT INTO `reserveaqui`.`mesa_reserva` (`mesa_id_mesa`, `reserva_id_reserva`, `id_status`) VALUES ('1', '1', '1');

INSERT INTO `reserveaqui`.`turno` (`id_turno`, `descricao`, `horario_inicio`, `horario_fim`) VALUES ('1', 'Manhã', '09:00:00', '12:00:00');
INSERT INTO `reserveaqui`.`turno` (`id_turno`, `descricao`, `horario_inicio`, `horario_fim`) VALUES ('2', 'Tarde', '13:00:00', '17:00:00');

INSERT INTO `reserveaqui`.`reserva_turno` (`reserva_id_reserva`, `turno_id_turno`) VALUES ('1', '1');

